In [1]:
import pandas as pd
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
data_dict = {}
for k in df_raw.columns:
    data_dict[k]=[1,]
data_dict

{'User_ID': [1],
 'Age': [1],
 'Gender': [1],
 'Height_cm': [1],
 'Initial_Weight_kg': [1],
 'Stress_Level': [1],
 'Sleep_Hours': [1],
 'Caffeine_mg': [1],
 'Calories_Consumed': [1],
 'Protein_g': [1],
 'Carbs_g': [1],
 'Fat_g': [1],
 'Steps': [1],
 'Workout_Type': [1],
 'Workout_Intensity': [1],
 'Temp_C': [1],
 'Weight_Change': [1],
 'Current_Weight_kg': [1]}

In [47]:
df_example = df_raw.iloc[[21,11,100,60,122],:].copy()
df_example.loc[0] = None
df_example['User_ID'] = -9
df_example.loc[0,'User_ID'] = 1
df_example.sort_index()
df_example.to_csv('df_example.csv')
df_example

/var/folders/3f/08kwcqtj2tj5p49_53tc3n_80000gn/T/ipykernel_68490/135568216.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  df_example.loc[0] = None

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
21,-9,25.0,Male,191.033652,108.533996,8.0,5.497507,314.300875,2825.787769,176.6,317.9,94.2,7994.0,Yoga,4.0,11.792555,0.246604,108.780600
11,-9,30.0,Male,171.400342,95.257466,1.0,6.468892,257.615042,NaN,123.1,221.7,65.7,8103.0,Strength,9.0,17.655289,0.023919,95.281385
100,-9,26.0,Female,169.037264,124.378046,1.0,7.789584,245.839295,2819.299321,176.2,317.2,94.0,8000.0,None,0.0,40.438666,0.248942,124.626988
60,-9,50.0,Female,163.363807,132.904201,7.0,8.480000,75.730706,1941.300065,121.3,218.4,64.7,8126.0,Yoga,9.0,20.741228,0.155379,133.059580
122,-9,62.0,Other,168.754397,141.301123,5.0,3.000000,354.356920,2085.573901,130.3,234.6,69.5,8033.0,Cardio,7.0,20.667504,0.134522,141.435646
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df_raw[df_raw['Workout_Type']=='Strength']

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
0,275,23,Female,169.355325,111.485330,10,7.016453,211.426469,2801.764291,175.1,315.2,93.4,8172,Strength,6,18.823955,0.317158,111.802488
11,172,30,Male,171.400342,95.257466,1,6.468892,257.615042,NaN,123.1,221.7,65.7,8103,Strength,9,17.655289,0.023919,95.281385
12,445,26,Male,155.269573,91.980743,3,7.191633,285.441830,3109.689661,194.4,349.8,103.7,7996,Strength,9,14.627410,0.197632,92.178375
20,532,31,Male,143.223804,96.517729,9,6.461002,306.335009,1370.254600,85.6,154.2,45.7,7954,Strength,9,18.332688,0.110608,96.628337
23,528,18,Male,159.045496,86.855575,3,5.600153,247.509188,2079.787602,130.0,234.0,69.3,8096,Strength,6,17.867329,0.079245,86.934820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54970,445,60,Female,184.830631,127.415285,5,8.973506,238.414682,2315.355085,144.7,260.5,77.2,8089,Strength,5,36.154603,0.241333,145.460393
54971,456,55,Male,169.790510,102.107849,7,6.702903,449.674181,3207.173200,200.4,360.8,106.9,8268,Strength,6,34.488274,0.387330,122.119998
54975,144,43,Male,166.541089,132.487285,2,8.424590,225.302679,3591.449517,224.5,404.0,119.7,8010,Strength,7,6.658103,0.200235,156.735568
54991,513,62,Female,153.274431,117.025571,5,6.458517,404.205272,1726.895294,107.9,194.3,57.6,7976,Strength,7,28.734880,0.128753,136.151872
54999,565,23,Male,175.664016,102.207143,10,10.402248,405.843037,1802.206215,112.6,202.7,60.1,7883,Strength,5,24.044327,0.215855,121.934377

In [2]:
df_raw = pd.read_csv('lifestyle weight tracker.csv')
df_raw

,User_ID,Age,Gender,Height_cm,Initial_Weight_kg,Stress_Level,Sleep_Hours,Caffeine_mg,Calories_Consumed,Protein_g,Carbs_g,Fat_g,Steps,Workout_Type,Workout_Intensity,Temp_C,Weight_Change,Current_Weight_kg
0,275,23,Female,169.355325,111.485330,10,7.016453,211.426469,2801.764291,175.1,315.2,93.4,8172,Strength,6,18.823955,0.317158,111.802488
1,296,43,Female,174.424939,109.699334,1,7.320227,211.979739,2666.001616,166.6,299.9,88.9,7988,None,0,36.987432,0.211877,109.911211
2,125,47,Male,163.246320,110.960286,3,7.238641,160.400067,1707.084012,106.7,192.0,56.9,7976,Yoga,10,35.977033,0.122390,111.082676
3,167,42,Female,164.997333,85.546097,7,5.060697,301.629856,2647.458547,165.5,297.8,88.2,8203,Cardio,10,33.141805,0.308449,85.854547
4,311,54,Male,167.696168,135.710505,5,9.866791,335.199126,2036.567163,127.3,229.1,67.9,8024,None,0,19.065076,0.120221,135.830726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54995,288,31,Female,172.989751,130.257318,6,5.791148,271.088251,2268.846150,141.8,255.2,75.6,7935,None,0,20.023635,0.175921,151.356362
54996,159,37,Male,179.688824,123.132106,9,7.691768,315.457575,1845.442138,115.3,207.6,61.5,7949,None,0,18.972702,0.175562,139.965519
54997,385,19,Female,167.302095,99.227392,3,8.340457,125.622338,NaN,150.0,269.9,80.0,7909,None,0,16.169056,0.113811,117.888421
54998,570,20,Male,178.401840,106.253039,10,5.833022,386.287965,2407.771582,150.5,270.9,80.3,7897,None,0,33.360536,0.340965,128.880845
54999,565,23,Male,175.664016,102.207143,10,10.402248,405.843037,1802.206215,112.6,202.7,60.1,7883,Strength,5,24.044327,0.215855,121.934377

In [8]:
df_clean = pd.DataFrame(index = df_raw.index)
df_clean['!age'] = df_raw['Age']/100
df_clean[['!gender_f','!gender_m','!gender_x']] = pd.get_dummies(df_raw, columns=['Gender', ])[['Gender_Female','Gender_Male','Gender_Other']]
df_clean['!height'] = df_raw['Height_cm'].apply(lambda x: (x-120)/100)
df_clean['!weight'] = df_raw['Initial_Weight_kg'].apply(lambda x: sigmoid(0.08*(x-120)))
df_clean['!stress'] = df_raw['Stress_Level']/10
df_clean['!sleep'] = df_raw['Sleep_Hours']/12
df_clean['!caffeine'] = df_raw['Caffeine_mg'].apply(lambda x: sigmoid(0.015*(x-260)))
df_clean['!calories'] = df_raw['Calories_Consumed'].fillna(df_raw['Calories_Consumed'].mean())/4200
df_clean.loc[df_clean['!calories']<0,['!calories']] = 0
df_clean['!protein'] = df_raw['Protein_g']/305
df_clean.loc[df_clean['!protein']<0,['!protein']] = 0
df_clean['!carbs'] = df_raw['Carbs_g']/480
df_clean.loc[df_clean['!carbs']<0,['!carbs']] = 0
df_clean['!fat'] = df_raw['Fat_g']/160
df_clean.loc[df_clean['!fat']<0,['!fat']] = 0
df_clean['!steps'] = (df_raw['Steps']-7600)/2500
df_clean[['!work_carb','!work_na','!work_strn','!work_yoga']] = pd.get_dummies(df_raw, columns=['Workout_Type', ])[
    ['Workout_Type_Cardio', 'Workout_Type_None', 'Workout_Type_Strength', 'Workout_Type_Yoga']
]
df_clean['!workintensity'] = df_raw['Workout_Intensity']/10
df_clean['!temp'] = df_raw['Temp_C'].apply(lambda x: sigmoid(-0.12*(x-20)))

df_clean['#y#'] = df_raw['Weight_Change']
df_clean

,!age,!gender_f,!gender_m,!gender_x,!height,!weight,!stress,!sleep,!caffeine,!calories,...,!carbs,!fat,!steps,!work_carb,!work_na,!work_strn,!work_yoga,!workintensity,!temp,#y#
0,0.23,1,0,0,0.493553,0.335999,1.0,0.584704,0.325501,0.667087,...,0.656667,0.583750,0.2288,0,0,1,0,0.6,0.535223,0.317158
1,0.43,1,0,0,0.544249,0.304904,0.1,0.610019,0.327326,0.634762,...,0.624792,0.555625,0.1552,0,1,0,0,0.0,0.115220,0.211877
2,0.47,0,1,0,0.432463,0.326694,0.3,0.603220,0.183322,0.406449,...,0.400000,0.355625,0.1504,0,0,0,1,1.0,0.128169,0.122390
3,0.42,1,0,0,0.449973,0.059731,0.7,0.421725,0.651229,0.630347,...,0.620417,0.551250,0.2412,1,0,0,0,1.0,0.171218,0.308449
4,0.54,0,1,0,0.476962,0.778482,0.5,0.822233,0.755467,0.484897,...,0.477292,0.424375,0.1696,0,1,0,0,0.0,0.528018,0.120221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54995,0.31,1,0,0,0.529898,0.694361,0.6,0.482596,0.541485,0.540201,...,0.531667,0.472500,0.1340,0,1,0,0,0.0,0.499291,0.175921
54996,0.37,0,1,0,0.596888,0.562316,0.9,0.640981,0.696749,0.439391,...,0.432500,0.384375,0.1396,0,1,0,0,0.0,0.530780,0.175562
54997,0.19,1,0,0,0.473021,0.159519,0.3,0.695038,0.117568,0.499459,...,0.562292,0.500000,0.1236,0,1,0,0,0.0,0.612946,0.113811
54998,0.20,0,1,0,0.584018,0.249785,1.0,0.486085,0.869247,0.573279,...,0.564375,0.501875,0.1188,0,1,0,0,0.0,0.167526,0.340965
54999,0.23,0,1,0,0.556640,0.194125,1.0,0.866854,0.899135,0.429097,...,0.422292,0.375625,0.1132,0,0,1,0,0.5,0.380997,0.215855

In [9]:
df_clean.to_csv('df_clean.csv')